name: Golang CI

on:
  push:
      branches: [main, dev]
  pull_request:
      branches: [main, dev]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.22', '1.21' ]
    name: Go ${{ matrix.go }} API
    steps:
      - uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - run: go run main.go
        working-directory: api
